
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class NPG extends javax.swing.JFrame {
    private GameManager mng;
    private boolean newGame=false;
    /**
     * Creates new form UI
     */
    public NPG() {
        initComponents();
        mng = new GameManager(this);
       // mng.addButton(3, pDisplay);
        mng.isStopGame(true);
        Thread elapsed=mng.elapsed();
        elapsed.start();
    }

    public JLabel getLbEclasped() {
        return lbEclasped;
    }

    public void setLbEclasped(String elasped) {
        this.lbEclasped.setText("Elapsed: "+elasped+" sec");
    }

    public JLabel getLbMoveCount() {
        return lbMoveCount;
    }

    public void setLbMoveCount(String count) {
        this.lbMoveCount.setText("Move count: "+count);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDisplay = new javax.swing.JPanel();
        lbMoveCount = new javax.swing.JLabel();
        lbEclasped = new javax.swing.JLabel();
        lbSiza = new javax.swing.JLabel();
        cbSize = new javax.swing.JComboBox();
        btnNewGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NPG");
        setResizable(false);

        javax.swing.GroupLayout pDisplayLayout = new javax.swing.GroupLayout(pDisplay);
        pDisplay.setLayout(pDisplayLayout);
        pDisplayLayout.setHorizontalGroup(
            pDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        pDisplayLayout.setVerticalGroup(
            pDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );

        lbMoveCount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMoveCount.setText("Move count: 0");

        lbEclasped.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbEclasped.setText("Elapsed: 0 sec");

        lbSiza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSiza.setText("Size");

        cbSize.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3x3", "4x4" }));
        cbSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSizeActionPerformed(evt);
            }
        });

        btnNewGame.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNewGame.setText("New game");
        btnNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSiza)
                                .addGap(47, 47, 47)
                                .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbEclasped)
                            .addComponent(lbMoveCount)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnNewGame))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(pDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbMoveCount)
                .addGap(18, 18, 18)
                .addComponent(lbEclasped)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSiza)
                    .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnNewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void cbSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSizeActionPerformed

    private void btnNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGameActionPerformed
        // TODO add your handling code here:
        if(this.lbEclasped.getText().equals("Elapsed: 0 sec") || mng.isWin()) {
            startGame();
        }else{
            int choose=JOptionPane.showConfirmDialog(this, "Are you sure to play new game?", "Confirm Dialog", JOptionPane.OK_CANCEL_OPTION);
            if(choose==0){
                startGame();
            }
        }
        
        
    }//GEN-LAST:event_btnNewGameActionPerformed

    public void startGame(){
        int index=cbSize.getSelectedIndex();
        System.out.println(index);
        int size;
        if(index==0){
            size=3;
        }else{
            size=4;
        }
        mng.addButton(size,pDisplay);
        mng.isStopGame(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NPG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NPG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewGame;
    private javax.swing.JComboBox cbSize;
    private javax.swing.JLabel lbEclasped;
    private javax.swing.JLabel lbMoveCount;
    private javax.swing.JLabel lbSiza;
    private javax.swing.JPanel pDisplay;
    // End of variables declaration//GEN-END:variables
}
// new 1 cai game moi, can xoa cai game cu + thread
// neu bam nut ko hop le thi count ko cong